_config.yml, _e-services/0-apply-online.md, _e-services/1-refer-a-case-to-cmc.md, _e-services/2-log-into-mediators-portal.md, pages/contact-us.md
Change eservices url for GCC migration on 24 Nov 2019.
=> Change of eservices url for GCC migration

_e-services/1-refer-a-case-to-cmc.md
Update CorpPass URL with FormSG URL
=> Update CorpPass URL with FormSG URL

_data/homepage.yml
change learn more to apply - as done by Indar
=> Change the link to Learn more

_data/homepage.yml, _data/navigation.yml
1) Updating Navigation 
2) Update homepage - Partner with us > Briefings for Organisation
=> Updating Website

_e-services/0-apply-online.md, _e-services/2-log-into-mediators-portal.md
=> Change in Singpass spelling

_partner-with-us/The CMC Mediators/our-mediators.md, index.md
=> Website update - 17082022

_about-us/CMC in Photos/macad-appointment-award-ceremony-2022.md
=> Update MACAD 2022 07112022_6

_about-us/CMC in Photos/macad-appointment-award-ceremony-2022.md, _partner-with-us/The CMC Mediators/list-of-appointed-cmc-mediators.md, _partner-with-us/The CMC Mediators/our-mediators.md
There is a typo... I have fix it.
=> Update our-mediators page

index.md
Change of the public consultation message since it has ended on 31 May
=> {"message":"Update file: index.md","fileName":"index.md","userId":"547"}

_e-services/refer-a-case-to-cmc.md
=> Refer a case to CMC

_e-services/refer-a-case-to-cmc.md
No 2
"you can" change to "please"
=> Refer a case to the CMC

index.md
=> COVID Banner removed

_e-services/apply-online.md
Address updated for 
- OnePunggol
- OTH
=> Address Updates

_e-services/refer-a-case-to-cmc.md
=> Link update

_data/footer.yml
=> Contact Us page update _V2

_partner-with-us/The CMC Mediators/CMC Volunteer Mediator Application Form.md
from volunteer CMC Mediator > CMC Volunteer Mediator
=> Changes to CMC Volunteer Mediators Application Form Page

_partner-with-us/The CMC Mediators/CMC Volunteer Mediator Application Form.md
=> Update on Volunteer Mediator Application Form Criteria 6

_partner-with-us/The CMC Mediators/CMC Volunteer Mediator Application Form.md
Criteria 6 has been amended from "You are actively involved in volunteer community work" to the approved by D (CM & MSC) and DD (CMU) statement of "You are currently / were active in community / voluntary work".
=> Volunteer Mediator Application, amendment to Criteria 6.

_e-services/Apply Online.md
=> number on apply online page

_partner-with-us/The CMC Mediators/list-of-appointed-cmc-mediators.md
=> Mediators List and Benefits of mediation

_partner-with-us/The CMC Mediators/List of Mediators Involved in GRCs or SMCs.md, _partner-with-us/The CMC Mediators/list-of-appointed-cmc-mediators.md
=> Updated Mediators List and Benefits of mediation

_about-us/CMC in Photos/gallery.md
=> CMC in Photos

_our-mediators/mediators-involved-in-grcs-smcs.md, _partner-with-us/The CMC Mediators/List of Mediators Involved in GRCs or SMCs.md
=> Mediators List update

_apply-for-mediation/Mediation at the CMC.md
=> Old Corporate video removed

_apply-for-mediation/Mediation at the CMC.md
New Corporate Video is embedded
=> New CMC's Corporate Video embedded

_apply-for-mediation/Mediation at the CMC.md
=> CORPORATE VIDEO REMOVED

_our-service/FAQs.md
=> FAQs page updated

_our-service/Post Mediation Process.md
Post mediation page is updated
=> Post mediation Page

_our-service/The CMC Mediation Process.md
=> THE ROADMAP

_our-service/FAQs.md
FAQs change ....." you can apply for Directed Remediation by calling....."
=> FAQs change ....." you can apply for Directed Remediation by calling....."

_our-mediators/Who are the CMC Mediators.md
=> Who are the CMC Mediators

_languages/Malay/Mohon Pengantaraan.md
Apply for mediation page and languages link updated
=> same link uploaded

_e-services/Apply for Mediation.md
- implemented the new link for direct remediation
=> Directed Remediation Link Updated
